@startuml

Actividad "0..n" <--* "n " Proyecto
Actividad <|-- Proyecto : hereda
Actividad <|-- Tarea : hereda
Tarea "1" <-- "1..n" Intervalo : dependencia >

Abstract Actividad {
-a_nombre
-a_LDT_fecha_inicial
-a_LDT_fecha_final
-a_fecha_inicial
-a_fecha_final
-a_tiempo_total
-a_proyecto_superior

+get_nombre()
+get_fecha_inicial()
+get_gecha_final()
+get_tiempo_total()
+get_proyecto_superior()
+set_nombre(name)
+set_fecha_inicial(start)
+set_fecha_final(finish)
+set_tiempo_total()
+a_mostrar()
}

Abstract Proyecto {
-p_lista_tareas
-p_lista_proyectos

+añadir_tarea(task)
+añadir_proyecto(proyect)
+eliminar_tarea(task)
+eliminar_proyecto(proyect)
+set_tiempo_total()
}

Class Tarea {
-t_lista_intervalos
-t_reloj

+t_get_Instance()
+set_tiempo_total()
+añadir_intervalo(interval)
+eliminar_interval(interval)
+start()
+stop()
}

Class Intervalo {
-i_LDT_fecha_inicio
-i_LDT_fecha_final
-i_fecha_inicio
-i_fecha_final
-i_tiempo_total
-i_tarea_superior

+i_get_fecha_inicial()
+i_get_fecha_final()
+i_get_tarea_superior()
+i_get_tiempo_total()
+i_set_fecha_inicial()
+i_set_fecha_final()
+i_mostrar()
+update()
}

Class Reloj {
-periodo
-uniqueinstance

+getInstance()
+Notify()
+run()
}

@enduml